# SPDX-License-Identifier: GPL-3.0-or-later
#
# rasterloomselftest: the embedded self-test (src/core/selftest/) plus the frozen golden corpus
# tests/goldens/ (tools/freeze_goldens.py), embedded at build time by cmake/EmbedFiles.cmake - one
# generated source per corpus directory so they compile in parallel. No Qt.

set(RL_GOLDENS_DIR "${PROJECT_SOURCE_DIR}/tests/goldens")
set(RL_SELFTEST_GEN "${CMAKE_CURRENT_BINARY_DIR}/selftest_gen")
file(MAKE_DIRECTORY "${RL_SELFTEST_GEN}")

# Corpus directories (plus "." for manifest.json). CONFIGURE_DEPENDS: a new domain re-configures.
file(GLOB RL_GOLDEN_ENTRIES CONFIGURE_DEPENDS LIST_DIRECTORIES true "${RL_GOLDENS_DIR}/*")
set(RL_GOLDEN_SUBDIRS ".")
foreach(e ${RL_GOLDEN_ENTRIES})
    if(IS_DIRECTORY "${e}")
        get_filename_component(d "${e}" NAME)
        list(APPEND RL_GOLDEN_SUBDIRS "${d}")
    endif()
endforeach()

set(RL_SELFTEST_GEN_SOURCES "")
set(RL_SELFTEST_DECLS "")
set(RL_SELFTEST_TABLES "")
foreach(sub ${RL_GOLDEN_SUBDIRS})
    if(sub STREQUAL ".")
        set(sym "Root")
        file(GLOB deps CONFIGURE_DEPENDS LIST_DIRECTORIES false "${RL_GOLDENS_DIR}/*")
    else()
        string(MAKE_C_IDENTIFIER "D_${sub}" sym)
        file(GLOB_RECURSE deps CONFIGURE_DEPENDS LIST_DIRECTORIES false "${RL_GOLDENS_DIR}/${sub}/*")
    endif()
    set(out "${RL_SELFTEST_GEN}/embed_${sym}.cpp")
    add_custom_command(OUTPUT "${out}"
        COMMAND "${CMAKE_COMMAND}" -DROOT=${RL_GOLDENS_DIR} -DSUBDIR=${sub} -DSYMBOL=${sym} -DOUT=${out}
                -P "${PROJECT_SOURCE_DIR}/cmake/EmbedFiles.cmake"
        DEPENDS ${deps} "${PROJECT_SOURCE_DIR}/cmake/EmbedFiles.cmake"
        COMMENT "Embedding golden corpus: ${sub}"
        VERBATIM)
    list(APPEND RL_SELFTEST_GEN_SOURCES "${out}")
    string(APPEND RL_SELFTEST_DECLS "extern const EmbeddedFile k${sym}[];\nextern const std::size_t k${sym}Count;\n")
    string(APPEND RL_SELFTEST_TABLES "        add(k${sym}, k${sym}Count);\n")
endforeach()

# The index collects every generated table into one sorted list.
set(RL_SELFTEST_INDEX "${RL_SELFTEST_GEN}/selftest_index.cpp")
set(idx "// Generated by src/core/selftest/selftest.cmake - do not edit.
// SPDX-License-Identifier: GPL-3.0-or-later
#include <algorithm>
#include <cstring>

#include \"core/selftest/embedded.hpp\"

namespace rl::selftest {
namespace embedded {
${RL_SELFTEST_DECLS}}  // namespace embedded

const std::vector<EmbeddedFile>& embedded_files() {
    static const std::vector<EmbeddedFile> all = [] {
        using namespace embedded;
        std::vector<EmbeddedFile> v;
        auto add = [&v](const EmbeddedFile* t, std::size_t n) {
            for (std::size_t i = 0; i < n; ++i)
                if (t[i].path) v.push_back(t[i]);
        };
${RL_SELFTEST_TABLES}        std::sort(v.begin(), v.end(),
                  [](const EmbeddedFile& a, const EmbeddedFile& b) { return std::strcmp(a.path, b.path) < 0; });
        return v;
    }();
    return all;
}

const EmbeddedFile* find_embedded(std::string_view path) {
    const auto& v = embedded_files();
    auto it = std::lower_bound(v.begin(), v.end(), path,
                               [](const EmbeddedFile& f, std::string_view p) { return std::string_view(f.path) < p; });
    return (it != v.end() && std::string_view(it->path) == path) ? &*it : nullptr;
}

}  // namespace rl::selftest
")
file(CONFIGURE OUTPUT "${RL_SELFTEST_INDEX}" CONTENT "${idx}" @ONLY)

add_library(rasterloomselftest STATIC
    "${CMAKE_CURRENT_LIST_DIR}/selftest.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/bench.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/bench.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/selftest.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/embedded.hpp"
    "${RL_SELFTEST_INDEX}"
    ${RL_SELFTEST_GEN_SOURCES})
target_link_libraries(rasterloomselftest PUBLIC rasterloomcore)
rl_warnings(rasterloomselftest)
