#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""gen_parity.py - generate docs/PARITY.md (and the README headline block) from data/parity.yaml,
refusing any functional/parity claim whose evidence did not PASS.

    gen_parity.py [--data data/parity.yaml] [--report tests/output/report.json]
                  [--ctest-junit build/ctest-junit.xml ...] [--out docs/PARITY.md]
                  [--readme README.md] [--check]

Evidence entries (required for status functional and parity):
    golden:<glob>   matched against the golden names in --report (a run_goldens.py report of a
                    normal, non-mutation run). At least one golden must match and every matched
                    golden must have status PASS.
    ctest:<glob>    matched against test names in --ctest-junit (`ctest --output-junit FILE`).
                    Repeat --ctest-junit to merge runs (for example the offscreen suite and the
                    Xvfb GUI run): a test is proven if it passed in some run and failed in none.
                    At least one test must match and every match must have run and passed.
Missing report/junit files make every claim that needs them a violation.

Headline numbers are computed here, never written by hand:
    Tier-0 coverage   covered tier-0 rows / all tier-0 rows (covered = functional or parity)
    Strict parity     parity rows / all rows
    Weighted coverage per data/parity.yaml `weights` (formula stated there); ceiling = the same
                      with every non-wontfix row covered.

--check: write nothing; exit 1 if docs/PARITY.md or the README block would change.
Exit: 0 ok; 1 validation failure (every violation printed) or --check drift; 2 usage error.
"""
from __future__ import annotations

import argparse
import fnmatch
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("gen_parity: PyYAML is required (apt install python3-yaml / pip install pyyaml)",
          file=sys.stderr)
    sys.exit(2)

REPO = Path(__file__).resolve().parents[1]
STATUSES = ("missing", "stub", "functional", "parity", "wontfix")
COVERED = ("functional", "parity")
ID_RE = re.compile(r"^([A-Z]+)-(\d{3})$")
BEGIN, END = "<!-- parity:begin (generated by tools/gen_parity.py; do not edit) -->", \
    "<!-- parity:end -->"


# --------------------------------------------------------------------------------------------
# Loading and schema
# --------------------------------------------------------------------------------------------
def load(path: Path) -> dict:
    data = yaml.safe_load(path.read_text())
    if not isinstance(data, dict) or not isinstance(data.get("rows"), list):
        raise SystemExit(f"gen_parity: {path}: expected a mapping with a 'rows' list")
    return data


def schema_errors(data: dict) -> list[str]:
    errs = []
    areas = data.get("areas") or {}
    w = data.get("weights") or {}
    aw = w.get("area") or {}
    tw = w.get("tier") or {}
    if set(tw) != {0, 1, 2} or any(not isinstance(v, (int, float)) or v <= 0
                                   for v in tw.values()):
        errs.append("weights.tier must give a positive weight for tiers 0, 1 and 2")
    if set(aw) != set(areas):
        errs.append(f"weights.area keys {sorted(aw)} != areas {sorted(areas)}")
    if abs(sum(aw.values()) - 1.0) > 1e-9:
        errs.append(f"weights.area must sum to 1.0 (sums to {sum(aw.values())!r})")
    seen = set()
    for i, r in enumerate(data["rows"]):
        where = f"row {i} ({r.get('id', '?')})"
        if not isinstance(r, dict):
            errs.append(f"{where}: not a mapping")
            continue
        extra = set(r) - {"id", "area", "name", "tier", "status", "evidence", "planned_evidence",
                          "wontfix_reason", "note"}
        if extra:
            errs.append(f"{where}: unknown keys {sorted(extra)}")
        m = ID_RE.match(str(r.get("id", "")))
        if not m:
            errs.append(f"{where}: id must look like AREA-NNN")
        elif m.group(1) != r.get("area"):
            errs.append(f"{where}: id prefix does not match area {r.get('area')!r}")
        if r.get("id") in seen:
            errs.append(f"{where}: duplicate id")
        seen.add(r.get("id"))
        if r.get("area") not in areas:
            errs.append(f"{where}: unknown area {r.get('area')!r}")
        if not isinstance(r.get("name"), str) or not r["name"].strip():
            errs.append(f"{where}: name must be a non-empty string")
        if r.get("tier") not in (0, 1, 2):
            errs.append(f"{where}: tier must be 0, 1 or 2")
        st = r.get("status")
        if st not in STATUSES:
            errs.append(f"{where}: status must be one of {STATUSES}")
        if (st == "wontfix") != bool(r.get("wontfix_reason")):
            errs.append(f"{where}: wontfix_reason is required for wontfix and only for wontfix")
        ev = r.get("evidence")
        if st in COVERED and not ev:
            errs.append(f"{where}: status {st} requires evidence")
        if st not in COVERED and ev:
            errs.append(f"{where}: evidence on a {st} row (use planned_evidence)")
        for key in ("evidence", "planned_evidence"):
            for e in r.get(key) or []:
                if not isinstance(e, str) or not re.match(r"^(golden|ctest):\S+$", e):
                    errs.append(f"{where}: {key} entry {e!r} must be golden:<glob> or "
                                "ctest:<glob>")
    return errs


# --------------------------------------------------------------------------------------------
# Evidence
# --------------------------------------------------------------------------------------------
class Evidence:
    def __init__(self, report: Path | None, junits: list[Path]):
        self.goldens: dict[str, str] | None = None
        self.ctests: dict[str, bool] | None = None
        self.report_meta = None
        self.junit_meta = None
        self.problems: list[str] = []
        if report and report.exists():
            rep = json.loads(report.read_text())
            if rep.get("mutate") is not None:
                self.problems.append(f"{report} is a mutation run (--mutate "
                                     f"{rep['mutate']}); evidence needs a normal run")
            else:
                self.goldens = {r["name"]: r["status"] for r in rep.get("results", [])}
                self.report_meta = {"generated": rep.get("generated"), "counts": rep.get("counts"),
                                    "scripts": rep.get("scripts"),
                                    "determinism": rep.get("determinism_checked")}
        present = [j for j in junits if j.exists()]
        if present:
            passed: set[str] = set()
            failed: set[str] = set()
            names: set[str] = set()
            stamps = []
            for junit in present:
                root = ET.parse(junit).getroot()
                stamps.append(root.get("timestamp"))
                for tc in root.iter("testcase"):
                    name = tc.get("name", "")
                    names.add(name)
                    tags = {ch.tag for ch in tc}
                    if tags & {"failure", "error"} or tc.get("status") == "fail":
                        failed.add(name)
                    elif tc.get("status") == "run" and "skipped" not in tags:
                        passed.add(name)
            # Skipped in one run and passed in another counts; a failure anywhere never does.
            self.ctests = {n: (n in passed and n not in failed) for n in names}
            self.junit_meta = {"tests": len(self.ctests),
                               "passed": sum(self.ctests.values()),
                               "timestamp": max((t for t in stamps if t), default=None)}

    def check(self, entry: str) -> str | None:
        """None if the entry is proven, else why not."""
        kind, pat = entry.split(":", 1)
        if kind == "golden":
            if self.goldens is None:
                return "no golden report"
            hits = {n: s for n, s in self.goldens.items() if fnmatch.fnmatchcase(n, pat)}
        else:
            if self.ctests is None:
                return "no ctest junit"
            hits = {n: ("PASS" if ok else "FAIL") for n, ok in self.ctests.items()
                    if fnmatch.fnmatchcase(n, pat)}
        if not hits:
            return "matches nothing"
        bad = sorted(n for n, s in hits.items() if s != "PASS")
        if bad:
            return f"{len(bad)} of {len(hits)} not PASS (e.g. {bad[0]}: {hits[bad[0]]})"
        return None


# --------------------------------------------------------------------------------------------
# Numbers
# --------------------------------------------------------------------------------------------
def headline(data: dict) -> dict:
    rows = data["rows"]
    tw = data["weights"]["tier"]
    aw = data["weights"]["area"]
    t0 = [r for r in rows if r["tier"] == 0]
    cov, ceil = 0.0, 0.0
    for area, w in aw.items():
        ar = [r for r in rows if r["area"] == area]
        tot = sum(tw[r["tier"]] for r in ar)
        if not tot:
            continue
        cov += w * sum(tw[r["tier"]] for r in ar if r["status"] in COVERED) / tot
        ceil += w * sum(tw[r["tier"]] for r in ar if r["status"] != "wontfix") / tot
    return {
        "rows": len(rows),
        "tier0": len(t0),
        "tier0_covered": sum(1 for r in t0 if r["status"] in COVERED),
        "parity": sum(1 for r in rows if r["status"] == "parity"),
        "functional": sum(1 for r in rows if r["status"] == "functional"),
        "wontfix": sum(1 for r in rows if r["status"] == "wontfix"),
        "stub": sum(1 for r in rows if r["status"] == "stub"),
        "missing": sum(1 for r in rows if r["status"] == "missing"),
        "strict_pct": 100.0 * sum(1 for r in rows if r["status"] == "parity") / len(rows),
        "weighted_pct": 100.0 * cov,
        "ceiling_pct": 100.0 * ceil,
    }


def headline_sentence(h: dict) -> str:
    return (f"Tier-0 coverage {h['tier0_covered']}/{h['tier0']}. Strict parity "
            f"{h['strict_pct']:.0f}% of {h['rows']} catalogued capabilities. Weighted "
            f"everyday-workflow coverage {h['weighted_pct']:.0f}%. Ceiling is "
            f"{h['ceiling_pct']:.0f}% - the remainder is server-side AI, patent-encumbered, "
            f"proprietary-model or discontinued features that will never be implemented.")


# --------------------------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------------------------
def _md(s: str) -> str:
    return str(s).replace("|", "\\|")


def render(data: dict, h: dict, ev: Evidence, hints: list[dict]) -> str:
    rows, areas = data["rows"], data["areas"]
    out = ["<!-- SPDX-License-Identifier: GPL-3.0-or-later -->",
           "<!-- Generated by tools/gen_parity.py from data/parity.yaml. Do not edit. -->",
           "", "# Rasterloom vs Photoshop: capability parity", "",
           "> " + headline_sentence(h), "",
           f"_{data.get('surface_note', '').strip()}_", "",
           "Rasterloom is an independent program, not affiliated with Adobe. The catalogue lists "
           "Photoshop capabilities as described in Adobe's public Photoshop User Guide; parity is "
           "asserted against written specifications (docs/math), never against Adobe output.", "",
           "## How these numbers are computed", "",
           "- **Tier-0 coverage**: tier-0 rows (\"if these are missing it is not Photoshop\") "
           "whose status is `functional` or `parity`, over all tier-0 rows.",
           "- **Strict parity**: rows with status `parity` over all catalogued rows "
           "(`wontfix` rows stay in the denominator).",
           "- **Weighted everyday-workflow coverage**: per-area share of tier-weighted covered "
           "rows, times the area weight. Tier weights "
           + ", ".join(f"tier {k} = {v}" for k, v in sorted(data['weights']['tier'].items()))
           + "; area weights: "
           + ", ".join(f"{a} {w:g}" for a, w in data["weights"]["area"].items()) + ".",
           "- **Ceiling**: the same weighted sum if every row except `wontfix` were covered.",
           "- A `stub` counts as missing. `functional`/`parity` rows cite evidence that passed in "
           "the test run below; the generator fails if any cited test did not pass.", ""]
    out += ["## Evidence run", ""]
    if ev.report_meta:
        m = ev.report_meta
        out.append(f"- Goldens: report generated {m['generated']}, {m['scripts']} scripts, "
                   f"counts {json.dumps(m['counts'], sort_keys=True)}, determinism checked: "
                   f"{m['determinism']}.")
    else:
        out.append("- Goldens: no report.")
    if ev.junit_meta:
        m = ev.junit_meta
        out.append(f"- CTest: {m['passed']} of {m['tests']} tests passed (junit timestamp "
                   f"{m['timestamp']}).")
    else:
        out.append("- CTest: no junit file.")
    out += ["", "## Totals", "",
            f"| rows | parity | functional | stub | missing | wontfix | tier-0 covered |",
            "|---:|---:|---:|---:|---:|---:|---:|",
            f"| {h['rows']} | {h['parity']} | {h['functional']} | {h['stub']} | {h['missing']} | "
            f"{h['wontfix']} | {h['tier0_covered']}/{h['tier0']} |", "",
            "## By area", "",
            "| area | title | weight | rows | tier-0 | covered | parity | wontfix |",
            "|---|---|---:|---:|---:|---:|---:|---:|"]
    for a, meta in areas.items():
        ar = [r for r in rows if r["area"] == a]
        out.append(f"| {a} | {_md(meta['title'])} | {data['weights']['area'][a]:g} | {len(ar)} | "
                   f"{sum(1 for r in ar if r['tier'] == 0)} | "
                   f"{sum(1 for r in ar if r['status'] in COVERED)} | "
                   f"{sum(1 for r in ar if r['status'] == 'parity')} | "
                   f"{sum(1 for r in ar if r['status'] == 'wontfix')} |")
    out += ["", "## Tier 0", "", "| id | capability | status | evidence |", "|---|---|---|---|"]
    for r in rows:
        if r["tier"] == 0:
            out.append(f"| {r['id']} | {_md(r['name'])} | {r['status']} | "
                       f"{_md(', '.join(r.get('evidence') or []))} |")
    if hints:
        out += ["", "## Promotion candidates", "",
                "Missing rows whose `planned_evidence` already passes in this run; promote them "
                "by moving the planned entries to `evidence` after checking the behaviour.", ""]
        out += [f"- {r['id']} {_md(r['name'])}: {', '.join(r['planned_evidence'])}" for r in hints]
    for a, meta in areas.items():
        out += ["", f"## {a}: {meta['title']}", "", f"Source: {meta['source']}.", "",
                "| id | capability | tier | status | evidence / reason / note |",
                "|---|---|---:|---|---|"]
        for r in rows:
            if r["area"] != a:
                continue
            info = []
            if r.get("evidence"):
                info.append("evidence: " + ", ".join(f"`{e}`" for e in r["evidence"]))
            if r.get("wontfix_reason"):
                info.append("wontfix: " + r["wontfix_reason"])
            if r.get("planned_evidence"):
                info.append("planned: " + ", ".join(f"`{e}`" for e in r["planned_evidence"]))
            if r.get("note"):
                info.append(r["note"])
            out.append(f"| {r['id']} | {_md(r['name'])} | {r['tier']} | {r['status']} | "
                       f"{_md('; '.join(info))} |")
    return "\n".join(out) + "\n"


def readme_block(h: dict) -> str:
    return (f"{BEGIN}\n> {headline_sentence(h)}\n>\n> Full table: [docs/PARITY.md](docs/PARITY.md) "
            f"({h['rows']} rows: {h['parity']} parity, {h['functional']} functional, "
            f"{h['missing'] + h['stub']} missing, {h['wontfix']} wontfix).\n{END}")


def splice_readme(text: str, block: str) -> str | None:
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < i:
        return None
    return text[:i] + block + text[j + len(END):]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 epilog=__doc__.split("\n", 1)[1])
    ap.add_argument("--data", default=str(REPO / "data/parity.yaml"))
    ap.add_argument("--report", default=str(REPO / "tests/output/report.json"))
    ap.add_argument("--ctest-junit", action="append", default=[], metavar="XML",
                    help="ctest --output-junit file; repeat to merge several runs")
    ap.add_argument("--out", default=str(REPO / "docs/PARITY.md"))
    ap.add_argument("--readme", default=None, metavar="README.md",
                    help="also rewrite the block between the parity markers in this file")
    ap.add_argument("--check", action="store_true", help="write nothing; exit 1 on drift")
    args = ap.parse_args(argv)

    data = load(Path(args.data))
    errs = schema_errors(data)
    ev = Evidence(Path(args.report) if args.report else None,
                  [Path(j) for j in args.ctest_junit])
    errs += [f"evidence input: {p}" for p in ev.problems]
    if not errs:
        for r in data["rows"]:
            for e in r.get("evidence") or []:
                why = ev.check(e)
                if why:
                    errs.append(f"{r['id']} ({r['name']}, {r['status']}): evidence {e}: {why}")
    if errs:
        for e in errs:
            print("VIOLATION " + e)
        print(f"gen_parity: {len(errs)} violation(s); nothing written")
        return 1

    hints = [r for r in data["rows"] if r["status"] in ("missing", "stub")
             and r.get("planned_evidence")
             and all(ev.check(e) is None for e in r["planned_evidence"])]
    h = headline(data)
    md = render(data, h, ev, hints)
    drift = []
    outp = Path(args.out)
    if not outp.exists() or outp.read_text() != md:
        drift.append(str(outp))
        if not args.check:
            outp.parent.mkdir(parents=True, exist_ok=True)
            outp.write_text(md)
    if args.readme:
        rp = Path(args.readme)
        new = splice_readme(rp.read_text(), readme_block(h))
        if new is None:
            print(f"gen_parity: {rp} has no parity marker block ({BEGIN} ... {END})")
            return 1
        if new != rp.read_text():
            drift.append(str(rp))
            if not args.check:
                rp.write_text(new)
    print(headline_sentence(h))
    print(f"rows {h['rows']}: parity {h['parity']}, functional {h['functional']}, stub "
          f"{h['stub']}, missing {h['missing']}, wontfix {h['wontfix']}; promotion candidates "
          f"{len(hints)}")
    if args.check:
        if drift:
            print("gen_parity --check: out of date: " + ", ".join(drift))
            return 1
        print("gen_parity --check: up to date")
    else:
        print("wrote " + (", ".join(drift) if drift else "nothing (already up to date)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
