#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""gen_third_party_notices.py - write THIRD-PARTY-NOTICES.md from data/third_party.yaml.

    gen_third_party_notices.py [--data data/third_party.yaml] [--out THIRD-PARTY-NOTICES.md]
                               [--set NAME=VERSION ...] [--allow-missing]

For each component the version is its fixed `version`, a --set override, or the first
`version_from` source that answers (pkg-config module or a command). The license text is the
first existing path in `license_files`, embedded verbatim. A component with no resolvable
version or no license text is an error (exit 1) unless --allow-missing, which writes the file
with a visible "UNRESOLVED" marker and still exits 1 - never ship such a file.

The output depends only on the manifest, the resolved versions and the license files (no
timestamps, no host names, no absolute home paths), so the release job can diff it.
"""
from __future__ import annotations

import argparse
import shlex
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("gen_third_party_notices: PyYAML is required", file=sys.stderr)
    sys.exit(2)

REPO = Path(__file__).resolve().parents[1]


def resolve_version(comp: dict, overrides: dict) -> tuple[str | None, str]:
    if comp["name"] in overrides:
        return overrides[comp["name"]], "--set"
    if comp.get("version"):
        return str(comp["version"]), "manifest"
    for src in comp.get("version_from", []):
        kind, arg = src.split(":", 1)
        cmd = ["pkg-config", "--modversion", arg] if kind == "pkg-config" else shlex.split(arg)
        try:
            cp = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True,
                                timeout=20)
        except (OSError, subprocess.TimeoutExpired):
            continue
        out = cp.stdout.strip().splitlines()
        if cp.returncode == 0 and out and out[0].strip():
            return out[0].strip(), src
    return None, "unresolved"


def resolve_license(comp: dict) -> Path | None:
    for cand in comp.get("license_files", []):
        p = Path(cand)
        if not p.is_absolute():
            p = REPO / p
        if p.is_file():
            return p
    return None


def display_path(p: Path) -> str:
    try:
        return p.relative_to(REPO).as_posix()
    except ValueError:
        return p.as_posix()  # system paths such as /usr/share/licenses/... are not personal


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 epilog=__doc__.split("\n", 1)[1])
    ap.add_argument("--data", default=str(REPO / "data/third_party.yaml"))
    ap.add_argument("--out", default=str(REPO / "THIRD-PARTY-NOTICES.md"))
    ap.add_argument("--set", action="append", default=[], metavar="NAME=VERSION")
    ap.add_argument("--allow-missing", action="store_true")
    args = ap.parse_args(argv)

    overrides = {}
    for s in args.set:
        if "=" not in s:
            ap.error(f"--set needs NAME=VERSION, got {s!r}")
        k, v = s.split("=", 1)
        overrides[k] = v
    comps = yaml.safe_load(Path(args.data).read_text())["components"]
    known = {c["name"] for c in comps}
    for k in overrides:
        if k not in known:
            ap.error(f"--set: unknown component {k!r}")

    problems, entries = [], []
    for c in comps:
        for key in ("name", "spdx", "url", "used_for"):
            if not c.get(key):
                problems.append(f"{c.get('name', '?')}: missing {key}")
        ver, src = resolve_version(c, overrides)
        lic = resolve_license(c)
        if ver is None:
            problems.append(f"{c['name']}: version unresolved (tried {c.get('version_from')})")
        if lic is None:
            problems.append(f"{c['name']}: no license text at {c.get('license_files')}")
        entries.append((c, ver, src, lic))

    out = ["# Third-party notices", "",
           "Rasterloom is licensed under GPL-3.0-or-later (see LICENSE). It ships or compiles in "
           "the components below, each under its own license. The full license texts follow the "
           "table. Generated by tools/gen_third_party_notices.py from data/third_party.yaml; do "
           "not edit by hand.", "",
           "| component | version | license (SPDX) | used for | homepage |",
           "|---|---|---|---|---|"]
    for c, ver, _src, _lic in entries:
        out.append(f"| {c['name']} | {ver or 'UNRESOLVED'} | {c['spdx']} | {c['used_for']} | "
                   f"{c['url']} |")
    for c, ver, _src, lic in entries:
        out += ["", "---", "", f"## {c['name']} {ver or 'UNRESOLVED'}", "",
                f"License: {c['spdx']}. Homepage: {c['url']}.", ""]
        if lic is None:
            out.append("**UNRESOLVED: license text not found.**")
            continue
        out += [f"License text (from `{display_path(lic)}`):", "", "```text",
                lic.read_text(encoding="utf-8", errors="replace").rstrip("\n")
                .replace("```", "'''"), "```"]
    text = "\n".join(out) + "\n"

    for c, ver, src, lic in entries:
        print(f"{c['name']:<60} {ver or 'UNRESOLVED':<10} via {src:<28} "
              f"{display_path(lic) if lic else 'NO LICENSE TEXT'}")
    if problems and not args.allow_missing:
        for p in problems:
            print("ERROR " + p)
        print("gen_third_party_notices: nothing written")
        return 1
    Path(args.out).write_text(text)
    print(f"wrote {args.out} ({len(entries)} components)")
    if problems:
        for p in problems:
            print("UNRESOLVED " + p)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
