# SPDX-License-Identifier: GPL-3.0-or-later
#
# Script mode (cmake -P): embeds every file of one directory into a generated C++ source as string
# literals, with no xxd (or any other external tool) dependency.
#
#   cmake -DROOT=<dir> -DSUBDIR=<name|.> -DSYMBOL=<c identifier> -DOUT=<file.cpp> -P EmbedFiles.cmake
#
# SUBDIR "."  : the regular files directly in ROOT (not recursive).
# SUBDIR name : every regular file under ROOT/name, recursively.
# Published path = path relative to ROOT with '/' separators. Files are emitted in sorted order, so
# the output is a pure function of the input bytes. The generated file defines
#   const rl::selftest::EmbeddedFile rl::selftest::embedded::k<SYMBOL>[];
#   const std::size_t rl::selftest::embedded::k<SYMBOL>Count;
# (declared in src/core/selftest/embedded.hpp). Each blob is NUL-terminated; `size` excludes it.

foreach(v ROOT SUBDIR SYMBOL OUT)
    if(NOT DEFINED ${v})
        message(FATAL_ERROR "EmbedFiles.cmake: -D${v}=... is required")
    endif()
endforeach()

if(SUBDIR STREQUAL ".")
    file(GLOB files LIST_DIRECTORIES false RELATIVE "${ROOT}" "${ROOT}/*")
else()
    file(GLOB_RECURSE files LIST_DIRECTORIES false RELATIVE "${ROOT}" "${ROOT}/${SUBDIR}/*")
endif()
list(SORT files)

set(body "")
set(table "")
set(i 0)
foreach(rel IN LISTS files)
    file(READ "${ROOT}/${rel}" hex HEX)
    string(LENGTH "${hex}" nhex)
    math(EXPR nbytes "${nhex} / 2")
    # 4096 bytes (8192 hex digits) per literal line; every byte as \xHH, so no escape can run into
    # a following hex digit.
    set(lines "")
    set(pos 0)
    while(pos LESS nhex)
        string(SUBSTRING "${hex}" ${pos} 8192 chunk)
        string(REGEX REPLACE "(..)" "\\\\x\\1" chunk "${chunk}")
        string(APPEND lines "    \"${chunk}\"\n")
        math(EXPR pos "${pos} + 8192")
    endwhile()
    if(nbytes EQUAL 0)
        set(lines "    \"\"\n")
    endif()
    string(APPEND body "// ${rel}\nconst char d${i}[] =\n${lines};\n")
    string(APPEND table "    {\"${rel}\", d${i}, ${nbytes}u},\n")
    math(EXPR i "${i} + 1")
endforeach()
if(i EQUAL 0)
    set(table "    {nullptr, nullptr, 0u},\n")
endif()

set(content "// Generated by cmake/EmbedFiles.cmake from ${SUBDIR} - do not edit.
// SPDX-License-Identifier: GPL-3.0-or-later
#include \"core/selftest/embedded.hpp\"

namespace rl::selftest::embedded {
namespace {
${body}}  // namespace

extern const EmbeddedFile k${SYMBOL}[] = {
${table}};
extern const std::size_t k${SYMBOL}Count = ${i};

}  // namespace rl::selftest::embedded
")

# Write only when changed, so an unchanged corpus does not recompile.
set(old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL content)
    file(WRITE "${OUT}" "${content}")
endif()
