#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""PSD/PSB and OpenRaster round-trip tests (BUILD-SPEC <verification> "PSD round-trip corpus").

    python3 tests/psd/roundtrip.py --cli build/src/rasterloom-cli --work build/tests/psd_rt \
        [--scripts tests/scripts/compositing]

Needs numpy, Pillow and psd-tools (run it with the project's .venv python). Exits 77 (CTest
"skipped") when psd-tools is missing.

Per corpus file F (generated by gen_corpus.py, an independent PSD writer):
  1. tree     --dump-tree F == --dump-tree (F -> out.psd): names, order, kinds, blend, opacity, fill,
              visibility, clip, masks, group boundaries, every node's foreign block keys + sha256
  2. stable   out.psd -> out2.psd is byte-identical (deterministic writer, idempotent re-save)
  3. blocks   a raw parser (below, independent of psd-tools and of our C++) compares per layer record
              the multiset of (key, bytes) of every tagged block the codec does not own, plus names,
              blend keys, opacity, clipping, visibility
  4. psdtools psd-tools reads the same structure from F and out.psd (name, kind, blend, opacity,
              clipping, visible, mask / vector-mask presence, fill, nesting)
  5. merged   out.psd has IRB 1057 with hasRealMergedData = 1; its Image Data section equals our own
              --render-file of out.psd (colour white-matted per psd.hpp, alpha exact, byte for byte);
              psd.composite() is non-black; psd-tools' un-matted topil() equals our render on every
              opaque pixel
  6. pixels   --render-file F == --render-file out.psd (byte-equal PNG pixels), and --render-file F
              agrees with psd-tools' own composite of F within a small tolerance (decode fidelity)
Per corpus file, OpenRaster:
  7. orp      F -> x.orp: render equal to F's, tree equal to F's, x.ora bytes == x.orp bytes,
              x.orp -> y.orp byte-identical, mimetype STORED at bytes 30/38, thumbnail <= 256,
              mergedimage.png == the render
Plus: a plain OpenRaster file without document.json (as GIMP/Krita write) opens with the expected
tree, and every compositing golden script saved as .orp re-opens to a byte-equal render.
"""
import argparse
import collections
import io
import json
import os
import struct
import subprocess
import sys
import zipfile

try:
    import numpy as np
    from PIL import Image
    import psd_tools.api.utils as psd_utils
    from psd_tools import PSDImage
    from psd_tools.constants import Resource
except ImportError as e:  # pragma: no cover
    print("SKIP: %s (run with the project's .venv python)" % e)
    sys.exit(77)

psd_utils.MAX_DIMENSION_PSD = 300000  # psd-tools refuses any side > 30000, even for PSB (research 2.1)

HERE = os.path.dirname(os.path.abspath(__file__))
OWNED = {b"luni", b"lsct", b"lsdk", b"iOpa", b"lspf", b"clbl"}
BIG = {b"LMsk", b"Lr16", b"Lr32", b"Layr", b"Mt16", b"Mt32", b"Mtrn", b"Alph", b"FMsk", b"lnk2", b"FEid",
       b"FXid", b"PxSD", b"cinf", b"lnk3", b"lnkE", b"extd", b"extn", b"pths", b"artd", b"FELS"}

failures = []
passes = 0


def check(cond, what):
    global passes
    if cond:
        passes += 1
    else:
        failures.append(what)
        print("FAIL:", what)


def run(cli, *args, capture=True):
    r = subprocess.run([cli, *args], capture_output=True)
    if r.returncode != 0:
        raise RuntimeError("%s %s -> %d: %s" % (os.path.basename(cli), " ".join(args), r.returncode,
                                                r.stderr.decode(errors="replace")))
    return r.stdout


def load_png(path):
    return np.asarray(Image.open(path).convert("RGBA"))


# ---- raw layer-record parser (Adobe spec; no psd-tools) --------------------------------------


def raw_layers(path):
    d = open(path, "rb").read()
    u = lambda f, o: struct.unpack_from(">" + f, d, o)
    psb = u("H", 4)[0] == 2
    L = 8 if psb else 4
    o = 26
    o += 4 + u("I", o)[0]  # colour mode data
    o += 4 + u("I", o)[0]  # image resources
    lm_len = u("Q" if psb else "I", o)[0]
    o += L
    lm_end = o + lm_len
    li_len = u("Q" if psb else "I", o)[0]
    o += L
    info = (o, o + li_len) if li_len else None
    if info is None:  # 16-bit files: layer info inside the global 'Lr16' block
        p = o
        p += 4 + u("I", p)[0]  # global layer mask info
        while p + 12 <= lm_end:
            key = d[p + 4:p + 8]
            big = psb and key in BIG
            ln = u("Q" if big else "I", p + 8)[0]
            p += 16 if big else 12
            if key in (b"Lr16", b"Lr32"):
                info = (p, p + ln)
                break
            p += ln + ((-ln) % 4)
    if info is None:
        return []
    o = info[0]
    n = abs(u("h", o)[0])
    o += 2
    out = []
    for _ in range(n):
        top, left, bottom, right = u("4i", o)
        o += 16
        nc = u("H", o)[0]
        o += 2 + nc * (2 + L)
        blend = d[o + 4:o + 8]
        opacity, clip, flags = d[o + 8], d[o + 9], d[o + 10]
        o += 12
        extra = u("I", o)[0]
        o += 4
        end = o + extra
        o += 4 + u("I", o)[0]
        o += 4 + u("I", o)[0]
        nl = d[o]
        pname = d[o + 1:o + 1 + nl]
        o += (1 + nl + 3) & ~3
        blocks = []
        while o + 12 <= end:
            key = d[o + 4:o + 8]
            big = psb and key in BIG
            ln = u("Q" if big else "I", o + 8)[0]
            o += 16 if big else 12
            blocks.append((key, d[o:o + ln]))
            o += ln
        o = end
        name = pname.decode("latin-1")
        for k, v in blocks:
            if k == b"luni":
                cnt = struct.unpack_from(">I", v, 0)[0]
                name = v[4:4 + 2 * cnt].decode("utf-16-be").rstrip("\0")
        out.append({"name": name, "blend": blend, "opacity": opacity, "clip": clip, "hidden": bool(flags & 2),
                    "blocks": collections.Counter((k, v) for k, v in blocks if k not in OWNED)})
    return out


# ---- psd-tools view ---------------------------------------------------------------------------


def tools_view(path):
    psd = PSDImage.open(path)
    rows = []

    def walk(g, depth):
        for layer in g:
            fill = 255
            tb = layer._record.tagged_blocks
            if tb is not None and b"iOpa" in [getattr(k, "value", k) for k in tb.keys()]:
                for k in tb.keys():
                    if getattr(k, "value", k) == b"iOpa":
                        fill = tb.get_data(k)
            rows.append((depth, layer.name.rstrip("\0"), layer.kind, str(layer.blend_mode), layer.opacity,
                         bool(layer.clipping), layer.visible, layer.has_mask(), layer.has_vector_mask(), fill))
            if layer.is_group():
                walk(layer, depth + 1)

    walk(psd, 0)
    return rows


def q(x):
    y = np.clip(x, 0.0, 1.0) * 255.0
    f = np.floor(y)
    return (f + ((y - f) >= 0.5)).astype(np.uint8)


def merged_checks(name, out_psd, render_png):
    psd = PSDImage.open(out_psd)
    vi = psd.image_resources.get_data(Resource.VERSION_INFO)
    check(vi is not None and vi.has_composite, "%s: IRB 1057 hasRealMergedData=1" % name)
    check(psd.image_resources.get_data(Resource.THUMBNAIL_RESOURCE) is not None, "%s: IRB 1036 thumbnail" % name)
    check(psd.image_resources.get_data(Resource.RESOLUTION_INFO) is not None, "%s: IRB 1005 resolution" % name)
    chans = psd._record.image_data.get_data(psd._record.header)
    check(len(chans) == 4, "%s: merged image has 4 channels (RGB + transparency)" % name)
    h, w = psd.height, psd.width
    planes = [np.frombuffer(c, dtype=np.uint8).reshape(h, w) for c in chans]
    ours = load_png(render_png)
    a = ours[..., 3].astype(np.float64) / 255.0
    ok = True
    for c in range(3):
        expect = q((ours[..., c].astype(np.float64) / 255.0) * a + (1.0 - a))
        ok = ok and np.array_equal(planes[c], expect)
    ok = ok and np.array_equal(planes[3], ours[..., 3])
    check(ok, "%s: merged Image Data == our --render-file (white-matted colour, exact alpha)" % name)
    comp = np.asarray(psd.composite())
    check(comp[..., :3].max() > 0, "%s: psd.composite() is non-black" % name)
    top = np.asarray(psd.topil().convert("RGBA"))
    opaque = ours[..., 3] == 255
    check(np.array_equal(top[opaque], ours[opaque]), "%s: psd-tools topil == our render on opaque pixels" % name)
    check(opaque.any() or ours[..., 3].max() == 0, "%s: render has content" % name)


def ora_checks(cli, name, src, work, ref_png, ref_tree):
    orp = os.path.join(work, name + ".orp")
    ora = os.path.join(work, name + ".ora")
    orp2 = os.path.join(work, name + ".2.orp")
    png = os.path.join(work, name + ".orp.png")
    run(cli, "--convert", src, orp)
    run(cli, "--convert", src, ora)
    run(cli, "--render-file", orp, "--out", png)
    check(np.array_equal(load_png(png), load_png(ref_png)), "%s: .orp render == source render" % name)
    tree = json.loads(run(cli, "--dump-tree", orp))
    check(tree == ref_tree, "%s: .orp tree (incl. foreign blocks) == source tree" % name)
    check(open(orp, "rb").read() == open(ora, "rb").read(), "%s: .ora and .orp bytes identical" % name)
    run(cli, "--convert", orp, orp2)
    b = open(orp, "rb").read()
    check(b == open(orp2, "rb").read(), "%s: .orp re-save byte-identical" % name)
    check(b[:4] == b"PK\x03\x04" and b[30:38] == b"mimetype" and b[38:54] == b"image/openraster"
          and struct.unpack_from("<H", b, 8)[0] == 0 and struct.unpack_from("<H", b, 28)[0] == 0,
          "%s: mimetype first, STORED, no extra field (magic at 30/38)" % name)
    z = zipfile.ZipFile(io.BytesIO(b))
    check(z.namelist()[0] == "mimetype" and "stack.xml" in z.namelist(), "%s: archive layout" % name)
    th = Image.open(io.BytesIO(z.read("Thumbnails/thumbnail.png")))
    check(max(th.size) <= 256 and th.mode == "RGBA", "%s: thumbnail <= 256 px" % name)
    merged = np.asarray(Image.open(io.BytesIO(z.read("mergedimage.png"))).convert("RGBA"))
    check(np.array_equal(merged, load_png(ref_png)), "%s: mergedimage.png == render" % name)
    for info in z.infolist():
        check(info.date_time == (1980, 1, 1, 0, 0, 0), "%s: %s has the fixed timestamp" % (name, info.filename))


def plain_ora(cli, work):
    """An OpenRaster file as GIMP/Krita write it: no document.json."""
    path = os.path.join(work, "plain.ora")

    def png_bytes(color, size):
        buf = io.BytesIO()
        Image.new("RGBA", size, color).save(buf, "PNG")
        return buf.getvalue()

    stack = ('<?xml version="1.0" encoding="UTF-8"?>\n<image version="0.0.5" w="40" h="30">\n<stack>\n'
             ' <stack name="pt" isolation="auto" opacity="0.5">\n'
             '  <layer name="clipped" src="data/c.png" x="0" y="0" composite-op="svg:src-atop"/>\n'
             '  <layer name="mul &amp; co" src="data/m.png" x="5" y="4" composite-op="svg:multiply"/>\n'
             ' </stack>\n'
             ' <layer name="lin" src="data/l.png" x="-3" y="2" opacity="0.75" composite-op="krita:linear_burn"'
             ' visibility="hidden"/>\n'
             ' <layer name="bg" src="data/bg.png" composite-op="svg:src-over"/>\n'
             '</stack>\n</image>\n')
    with zipfile.ZipFile(path, "w") as z:
        z.writestr(zipfile.ZipInfo("mimetype"), "image/openraster", compress_type=zipfile.ZIP_STORED)
        z.writestr("stack.xml", stack, compress_type=zipfile.ZIP_DEFLATED)
        z.writestr("data/bg.png", png_bytes((250, 250, 250, 255), (40, 30)))
        z.writestr("data/l.png", png_bytes((0, 0, 200, 255), (10, 10)))
        z.writestr("data/m.png", png_bytes((200, 100, 0, 255), (20, 20)))
        z.writestr("data/c.png", png_bytes((0, 200, 0, 128), (40, 30)))
        z.writestr("mergedimage.png", png_bytes((0, 0, 0, 255), (40, 30)))
    tree = json.loads(run(cli, "--dump-tree", path))
    kids = tree["children"]
    got = [(k["name"], k["kind"], k["blend"], k.get("visible")) for k in kids]
    check(got == [("bg", "raster", "norm", True), ("lin", "raster", "lbrn", False), ("pt", "group", "pass", True)],
          "plain.ora: top-level tree %s" % got)
    inner = [(k["name"], k["blend"], k.get("clip")) for k in kids[2]["children"]]
    check(inner == [("mul & co", "mul", False), ("clipped", "norm", True)], "plain.ora: group children %s" % inner)
    check(kids[1]["bbox"] == [0, 2, 7, 10], "plain.ora: negative x offset clipped to the canvas (%s)" % kids[1]["bbox"])
    run(cli, "--render-file", path, "--out", os.path.join(work, "plain.png"))


def goldens_orp(cli, scripts, work):
    n = 0
    for fn in sorted(os.listdir(scripts)):
        if not fn.endswith(".json"):
            continue
        s = os.path.join(scripts, fn)
        a = os.path.join(work, "g.a.png")
        b = os.path.join(work, "g.b.png")
        doc = os.path.join(work, "g.orp")
        for p in (a, b, doc):
            if os.path.exists(p):
                os.remove(p)
        r = subprocess.run([cli, "--render-script", s, "--out", a, "--save-doc", doc], capture_output=True)
        if r.returncode != 0:
            continue  # error goldens / ops of other lanes
        run(cli, "--render-file", doc, "--out", b)
        check(np.array_equal(load_png(a), load_png(b)), "golden %s: .orp re-open renders byte-equal" % fn)
        n += 1
    print("goldens round-tripped through .orp: %d" % n)
    check(n > 0, "at least one golden script rendered")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cli", required=True)
    ap.add_argument("--work", required=True)
    ap.add_argument("--scripts", default=None)
    args = ap.parse_args()
    cli = os.path.abspath(args.cli)
    work = os.path.abspath(args.work)
    corpus = os.path.join(work, "corpus")
    rt = os.path.join(work, "rt")
    os.makedirs(rt, exist_ok=True)
    subprocess.run([sys.executable, os.path.join(HERE, "gen_corpus.py"), corpus], check=True)
    files = sorted(os.listdir(corpus))
    check(len(files) == 12, "corpus has 12 files (%d)" % len(files))
    per_file_ok = 0
    for fn in files:
        before = len(failures)
        name = os.path.splitext(fn)[0]
        src = os.path.join(corpus, fn)
        try:
            out = os.path.join(rt, name + ".out.psd")
            out2 = os.path.join(rt, name + ".out2.psd")
            a = json.loads(run(cli, "--dump-tree", src))
            run(cli, "--convert", src, out)
            b = json.loads(run(cli, "--dump-tree", out))
            check(a == b, "%s: --dump-tree identical after open -> save -> reopen" % name)
            run(cli, "--convert", out, out2)
            check(open(out, "rb").read() == open(out2, "rb").read(), "%s: re-save byte-identical" % name)
            if max(a["w"], a["h"]) > 30000:
                check(struct.unpack_from(">H", open(out, "rb").read(), 4)[0] == 2, "%s: promoted to PSB" % name)
            ra, rb = raw_layers(src), raw_layers(out)
            check(len(ra) == len(rb), "%s: layer record count %d vs %d" % (name, len(ra), len(rb)))
            for i, (x, y) in enumerate(zip(ra, rb)):
                check(x["blocks"] == y["blocks"], "%s: record %d '%s' unparsed tagged blocks byte-identical (%s vs %s)"
                      % (name, i, x["name"], sorted(k for k, _ in x["blocks"]), sorted(k for k, _ in y["blocks"])))
                same = all(x[k] == y[k] for k in ("name", "opacity", "clip", "hidden"))
                check(same, "%s: record %d name/opacity/clip/visibility" % (name, i))
                check(x["blend"] == y["blend"] or (x["blend"] == b"pass" and y["blend"] == b"pass"),
                      "%s: record %d blend key %r vs %r" % (name, i, x["blend"], y["blend"]))
            check(tools_view(src) == tools_view(out), "%s: psd-tools structure identical" % name)
            if name == "layer_style":
                styled = [lay for lay in PSDImage.open(out).descendants() if lay.name == "styled"]
                check(len(styled) == 1 and styled[0].has_effects(), "layer_style: psd-tools sees the drop shadow")
            if name == "text_layer":
                t = [lay for lay in PSDImage.open(out).descendants() if lay.kind == "type"]
                check(len(t) == 1 and t[0].text == "Rl\r", "text_layer: psd-tools reads the text layer back")
            if name == "smart_object":
                so = [lay for lay in PSDImage.open(out).descendants() if lay.kind == "smartobject"]
                check(len(so) == 1 and so[0].smart_object.filename == "inner.png",
                      "smart_object: psd-tools resolves the smart object via lnk2")
            rsrc = os.path.join(rt, name + ".src.png")
            rout = os.path.join(rt, name + ".out.png")
            run(cli, "--render-file", src, "--out", rsrc)
            run(cli, "--render-file", out, "--out", rout)
            check(np.array_equal(load_png(rsrc), load_png(rout)), "%s: render(source) == render(saved)" % name)
            # Decode fidelity against an external reader: our render of the SOURCE vs psd-tools'
            # own layer compositing (float32, so a tolerance). Vector masks are not rendered by
            # Rasterloom (parity gap), and psd-tools converts CMYK with a different formula.
            tol = {"mask_vector": None, "cmyk": 8}.get(name, 2)
            if tol is not None:
                theirs = np.asarray(PSDImage.open(src).composite(force=True).convert("RGBA")).astype(int)
                ours = load_png(rsrc).astype(int)
                both = (ours[..., 3] == 255) & (theirs[..., 3] == 255)
                diff = int(np.abs(ours - theirs)[both][:, :3].max()) if both.any() else 0
                check(both.sum() > 0.5 * both.size or name == "psb_30001",
                      "%s: opaque overlap with psd-tools composite" % name)
                check(diff <= tol, "%s: our render of the source within %d of psd-tools' composite (max %d)"
                      % (name, tol, diff))
            merged_checks(name, out, rout)
            ora_checks(cli, name, src, rt, rsrc, a)
        except Exception as e:  # noqa: BLE001 - report and continue
            check(False, "%s: exception %s" % (name, e))
        if len(failures) == before:
            per_file_ok += 1
            print("PASS: %s" % fn)
    plain_ora(cli, rt)
    if args.scripts:
        goldens_orp(cli, args.scripts, rt)
    print("\nPSD round-trips passing: %d/%d files; checks passed %d, failed %d"
          % (per_file_ok, len(files), passes, len(failures)))
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
